export interface RumouredDeal {
  id: string;
  acquirerTicker: string;
  acquirerName: string;
  acquirerLogo: string;
  targetTicker: string;
  targetName: string;
  targetLogo: string;
  dealType: "Merger" | "Acquisition" | "Buyout" | "PE Deal" | "Strategic Review";
  estimatedValue: string;
  estimatedValueNum: number; // in billions, for sorting
  summary: string;
  source: string;
  dateRumoured: string;
  status: "Rumour" | "Talks Confirmed" | "Under Review";
  sector: string;
  dealProbability: number;
  probabilityRationale: string;
  keyStats: {
    acquirerMarketCap: string;
    targetMarketCap: string;
    estimatedPremium: string;
    sectorAvgMultiple: string;
  };
}

// Sorted by estimatedValueNum descending (largest deal first)
// Last refreshed: 8 May 2026
// Note: Devon/Coterra merger COMPLETED 7 May 2026 — removed from this list
export const rumouredDeals: RumouredDeal[] = [
  {
    id: "paramount-wbd",
    acquirerTicker: "PARA",
    acquirerName: "Paramount",
    acquirerLogo: "https://logo.clearbit.com/paramount.com",
    targetTicker: "WBD",
    targetName: "Warner Bros. Discovery",
    targetLogo: "https://logo.clearbit.com/wbd.com",
    dealType: "Acquisition",
    estimatedValue: "$110.9B",
    estimatedValueNum: 110.9,
    summary: "WBD shareholders approved Paramount Skydance's $111 billion takeover on 23 April 2026 with an overwhelming 1.743 billion votes in favour. The deal — valued at $31 per WBD share in cash — still requires DOJ and FCC clearance. The EU completed Phase 1 antitrust review on 29 April 2026. Paramount disclosed that the combined company will be 49.5% owned by Middle Eastern sovereign wealth funds: Saudi PIF (15.1%), UAE sovereign fund (12.8%), and Qatar Investment Authority (10.6%), drawing FCC Commissioner scrutiny and prompting multiple state AGs to issue subpoenas. Paramount has filed a Section 310(b)(4) FCC petition for the foreign ownership stake. Close is targeted for Q3 2026, though regulatory complexity — DOJ, FCC, multiple state AG investigations — could push this to Q1 2027.",
    source: "Variety / NPR / MLex",
    dateRumoured: "2025-12",
    status: "Talks Confirmed",
    sector: "Media / Entertainment",
    dealProbability: 75,
    probabilityRationale: "Shareholders approved April 23; EU Phase 1 cleared. DOJ, FCC, and state AG scrutiny of 49.5% Middle Eastern ownership is the key remaining risk — could delay to Q1 2027.",
    keyStats: {
      acquirerMarketCap: "$4.5B",
      targetMarketCap: "$15.8B",
      estimatedPremium: "34%",
      sectorAvgMultiple: "7.8x EV/EBITDA",
    },
  },
  {
    id: "up-nsc",
    acquirerTicker: "UNP",
    acquirerName: "Union Pacific",
    acquirerLogo: "https://logo.clearbit.com/up.com",
    targetTicker: "NSC",
    targetName: "Norfolk Southern",
    targetLogo: "https://logo.clearbit.com/nscorp.com",
    dealType: "Merger",
    estimatedValue: "$85B",
    estimatedValueNum: 85,
    summary: "Union Pacific's proposed acquisition of Norfolk Southern would create the first transcontinental freight railroad in US history — combining Union Pacific's 32,000-route-mile western system with Norfolk Southern's 19,500-route-mile eastern network. The $85 billion combined enterprise value makes this the largest proposed railroad merger since Burlington Northern Santa Fe in 1995, with management projecting $1 billion per year in cost synergies. The deal has unusual political support: SMART-TD, the largest railroad union, formally backed the combination, and President Trump publicly endorsed it. The Surface Transportation Board (STB) rejected the initial merger application as procedurally incomplete; Union Pacific submitted notice of intent to refile in April 2026. Key opposition includes the Teamsters and passenger rail advocates. The STB's multi-year review process means final regulatory resolution is unlikely before 2027-2028.",
    source: "Reuters / Axios",
    dateRumoured: "2025-06",
    status: "Under Review",
    sector: "Transportation / Infrastructure",
    dealProbability: 30,
    probabilityRationale: "STB rejected initial application; Union Pacific refiling April 2026 — multi-year review ahead, regulatory outcome highly uncertain.",
    keyStats: {
      acquirerMarketCap: "$135B",
      targetMarketCap: "$55B",
      estimatedPremium: "25%",
      sectorAvgMultiple: "14.2x EV/EBITDA",
    },
  },
  {
    id: "musk-openai",
    acquirerTicker: "PRIVATE",
    acquirerName: "Elon Musk Consortium",
    acquirerLogo: "https://logo.clearbit.com/x.com",
    targetTicker: "PRIVATE",
    targetName: "OpenAI",
    targetLogo: "https://logo.clearbit.com/openai.com",
    dealType: "Acquisition",
    estimatedValue: "$97.4B",
    estimatedValueNum: 97.4,
    summary: "In February 2025, Elon Musk — alongside a16z and other venture backers — submitted an unsolicited $97.4 billion all-cash bid for OpenAI during its contentious restructuring from a nonprofit to a Public Benefit Corporation. OpenAI's board unanimously rejected the offer, with CEO Sam Altman calling it a strategic distraction. The bid was widely seen as below fair value: OpenAI completed its for-profit restructuring with SoftBank's $40 billion investment at a $260 billion valuation in late 2025. Musk's lawsuit alleging that Sam Altman and Microsoft deviated from OpenAI's founding nonprofit mission was cleared for a jury trial, which began March 30, 2026. A ruling against OpenAI could force structural changes to its for-profit conversion, potentially reopening restructuring scenarios. OpenAI faces approximately $14 billion in projected operating losses in 2026, renewing debate about whether a future strategic transaction remains plausible.",
    source: "Wall Street Journal / Bloomberg",
    dateRumoured: "2025-02",
    status: "Under Review",
    sector: "Artificial Intelligence / Technology",
    dealProbability: 12,
    probabilityRationale: "Board rejected the bid; Musk vs OpenAI trial ongoing from March 2026 — court outcome could reopen restructuring scenarios but full acquisition remains unlikely near-term.",
    keyStats: {
      acquirerMarketCap: "Private",
      targetMarketCap: "$260B (last round)",
      estimatedPremium: "N/A",
      sectorAvgMultiple: "N/A",
    },
  },
  {
    id: "charter-cox",
    acquirerTicker: "CHTR",
    acquirerName: "Charter Communications",
    acquirerLogo: "https://logo.clearbit.com/charter.com",
    targetTicker: "PRIVATE",
    targetName: "Cox Communications",
    targetLogo: "https://logo.clearbit.com/cox.com",
    dealType: "Acquisition",
    estimatedValue: "$34.5B",
    estimatedValueNum: 34.5,
    summary: "Charter Communications is acquiring Cox Enterprises' cable, commercial fiber, and cloud communications businesses for $34.5 billion — the largest US cable consolidation since Charter's own Time Warner Cable acquisition in 2016. The FCC Wireline Competition Bureau approved the deal on 27 February 2026, with conditions including US job preservation, a $20/hour minimum starting wage for Cox workers, and onshoring of all offshore job functions within 18 months. The DOJ and states including New York and Connecticut have cleared the transaction. California's Public Utilities Commission is the sole remaining approval, with evidentiary hearings completed 20-24 April 2026. Charter has formally requested the California PUC to accelerate its review ahead of the September 15, 2026 federal merger condition deadline. The combined company will be the largest US internet service provider with over 37 million broadband subscribers, operating under the Cox name with the Spectrum consumer brand.",
    source: "Deadline / FCC",
    dateRumoured: "2025-05",
    status: "Talks Confirmed",
    sector: "Telecommunications / Cable",
    dealProbability: 85,
    probabilityRationale: "FCC approved February 2026; California PUC hearings concluded April 2026 — final approval imminent ahead of September 2026 federal deadline.",
    keyStats: {
      acquirerMarketCap: "$48B",
      targetMarketCap: "N/A (private)",
      estimatedPremium: "N/A",
      sectorAvgMultiple: "9.1x EV/EBITDA",
    },
  },
  {
    id: "qxo-topbuild",
    acquirerTicker: "QXO",
    acquirerName: "QXO",
    acquirerLogo: "https://logo.clearbit.com/qxo.com",
    targetTicker: "BLD",
    targetName: "TopBuild",
    targetLogo: "https://logo.clearbit.com/topbuild.com",
    dealType: "Acquisition",
    estimatedValue: "$17B",
    estimatedValueNum: 17,
    summary: "QXO announced a definitive agreement to acquire TopBuild Corp for approximately $17 billion on April 19, 2026 — the largest deal in the building products distribution sector in decades. TopBuild is the largest distributor and installer of insulation and related building products in North America. Under the terms, TopBuild stockholders can elect $505 in cash or 20.2 QXO shares per TopBuild share, with total consideration approximately 45% cash and 55% QXO stock. The $505 per share price represents a 23.1% premium to TopBuild's closing price on April 17, 2026. The deal has been unanimously approved by both boards. Upon closing, QXO will become the second largest publicly traded building products distributor in North America with over $18 billion in combined revenue and $2 billion in adjusted EBITDA. QXO CEO Brad Jacobs — who previously built XPO Logistics into a $35 billion company — has identified building products distribution as the platform for his next multi-decade rollup strategy, targeting $50 billion in sales. The acquisition is expected to close in Q3 2026.",
    source: "Bloomberg / QXO IR",
    dateRumoured: "2026-04",
    status: "Talks Confirmed",
    sector: "Industrials / Building Products",
    dealProbability: 88,
    probabilityRationale: "Definitive agreement signed April 19, 2026; unanimously approved by both boards — Q3 2026 close expected, no major antitrust concerns.",
    keyStats: {
      acquirerMarketCap: "$18B",
      targetMarketCap: "$14B",
      estimatedPremium: "23%",
      sectorAvgMultiple: "11.2x EV/EBITDA",
    },
  },
  {
    id: "merck-rvmd",
    acquirerTicker: "MRK",
    acquirerName: "Merck",
    acquirerLogo: "https://logo.clearbit.com/merck.com",
    targetTicker: "RVMD",
    targetName: "Revolution Medicines",
    targetLogo: "https://logo.clearbit.com/revmed.com",
    dealType: "Acquisition",
    estimatedValue: "$30B",
    estimatedValueNum: 30,
    summary: "The Financial Times reported in January 2026 that Merck is in advanced acquisition talks with Revolution Medicines, the South San Francisco-based oncology biotech, in a deal that could value RVMD at between $28 billion and $32 billion — potentially the largest biotech acquisition since Pfizer's $43 billion purchase of Seagen in 2023. Bloomberg subsequently confirmed the discussions. The strategic rationale is existential: Keytruda — Merck's flagship PD-1 cancer immunotherapy generating over $25 billion in annual revenue — faces biosimilar competition following US patent expiry in 2028. Revolution Medicines' RAS(ON) inhibitor platform targets KRAS-mutant cancers which account for approximately 25% of all human cancers. Lead assets RMC-6236 (pan-RAS) and RMC-6291 (KRAS G12C-selective) are in Phase 2/3 trials showing compelling early efficacy. Revolution Medicines shares rose approximately 40% on the initial FT report. No formal announcement as of May 2026.",
    source: "Financial Times / Bloomberg",
    dateRumoured: "2026-01",
    status: "Rumour",
    sector: "Pharmaceuticals / Oncology",
    dealProbability: 45,
    probabilityRationale: "Advanced talks confirmed by FT and Bloomberg; no formal deal yet — Merck weighing price against urgency of the 2028 Keytruda patent cliff.",
    keyStats: {
      acquirerMarketCap: "$260B",
      targetMarketCap: "$8.5B",
      estimatedPremium: "40%",
      sectorAvgMultiple: "N/A (pre-revenue)",
    },
  },
  {
    id: "amazon-globalstar",
    acquirerTicker: "AMZN",
    acquirerName: "Amazon",
    acquirerLogo: "https://logo.clearbit.com/amazon.com",
    targetTicker: "GSAT",
    targetName: "Globalstar",
    targetLogo: "https://logo.clearbit.com/globalstar.com",
    dealType: "Acquisition",
    estimatedValue: "$11.6B",
    estimatedValueNum: 11.6,
    summary: "Amazon agreed on 14 April 2026 to acquire satellite operator Globalstar in an $11.6 billion all-cash deal at $90 per share, enabling the creation of Amazon Leo — a direct-to-device (D2D) low Earth orbit satellite network. The acquisition gives Amazon proprietary spectrum and direct-to-device technology, replacing its previous reliance on Globalstar's satellite network under a commercial agreement. Amazon simultaneously announced a partnership with Apple for Amazon Leo to power satellite-based Emergency SOS and connectivity services for iPhone and Apple Watch, providing immediate large-scale commercial demand. Amazon's satellite deployment roadmap targets service launch in 2028. Close is expected in late 2026 or early 2027, pending FCC spectrum approval and standard antitrust clearance.",
    source: "CNBC / Bloomberg / About Amazon",
    dateRumoured: "2026-04",
    status: "Talks Confirmed",
    sector: "Technology / Satellite",
    dealProbability: 82,
    probabilityRationale: "Definitive agreement signed April 14, 2026; Apple partnership provides commercial demand signal — FCC spectrum approval is the key regulatory gating factor.",
    keyStats: {
      acquirerMarketCap: "$2.1T",
      targetMarketCap: "$3.5B",
      estimatedPremium: "~100%",
      sectorAvgMultiple: "N/A",
    },
  },
  {
    id: "gilead-tubulis",
    acquirerTicker: "GILD",
    acquirerName: "Gilead Sciences",
    acquirerLogo: "https://logo.clearbit.com/gilead.com",
    targetTicker: "PRIVATE",
    targetName: "Tubulis",
    targetLogo: "https://logo.clearbit.com/tubulis.com",
    dealType: "Acquisition",
    estimatedValue: "$5B",
    estimatedValueNum: 5,
    summary: "Gilead Sciences announced on April 7, 2026 that it will acquire Tubulis, a Munich-based clinical-stage biotech specialising in next-generation antibody-drug conjugates (ADCs), for $3.15 billion in upfront cash plus up to $1.85 billion in contingent milestone payments — a total deal value of up to $5 billion. The acquisition is expected to close in Q2 2026. Tubulis' two lead programs — TUB-040 (NaPi2b-directed, targeting ovarian cancer and NSCLC) and TUB-030 (5T4-directed) — are in Phase 1b/2 development showing a 59% overall response rate in platinum-resistant ovarian cancer. Following close, Tubulis will operate as a dedicated ADC research hub within Gilead, with its Munich site serving as the centre of Gilead's ADC innovation platform. The deal extends a significant M&A spree for Gilead, which has also agreed to pay $7.8 billion for Arcellx and $2.18 billion for Ouro Medicines in recent months, signalling a major strategic pivot toward oncology and immunology.",
    source: "BioPharma Dive / STAT News",
    dateRumoured: "2026-04",
    status: "Talks Confirmed",
    sector: "Pharmaceuticals / Oncology",
    dealProbability: 90,
    probabilityRationale: "Definitive agreement announced April 7, 2026; Q2 2026 close expected — no antitrust concerns given Tubulis is pre-revenue.",
    keyStats: {
      acquirerMarketCap: "$100B",
      targetMarketCap: "Private",
      estimatedPremium: "N/A (private)",
      sectorAvgMultiple: "N/A (pre-revenue)",
    },
  },
  {
    id: "silgan-gerresheimer",
    acquirerTicker: "SLGN",
    acquirerName: "Silgan Holdings",
    acquirerLogo: "https://logo.clearbit.com/silgan.com",
    targetTicker: "GXI",
    targetName: "Gerresheimer",
    targetLogo: "https://logo.clearbit.com/gerresheimer.com",
    dealType: "Acquisition",
    estimatedValue: "$6.3B",
    estimatedValueNum: 6.3,
    summary: "US packaging company Silgan Holdings submitted a non-binding takeover approach for German pharmaceutical packaging group Gerresheimer, valuing the company at €41 per share — more than double its then-prevailing share price, at an implied enterprise value of approximately $6.3 billion. Gerresheimer's supervisory board rejected the bid on April 17, 2026, citing its intention to focus on resolving ongoing accounting irregularities and the sale of its US subsidiary Centor before pursuing any transaction. German financial watchdog BaFin has widened its examination of Gerresheimer's accounts; holders representing 96% of the €870 million promissory note volume agreed to extend the deadline for audited 2025 financial statements to September 30, 2026. Despite the rejection, analysts note that Gerresheimer remains a compelling strategic target — it is one of the world's largest manufacturers of glass and plastic packaging for the pharmaceutical industry, including primary packaging for GLP-1 drugs such as Ozempic and Mounjaro. With those markets growing rapidly, Silgan is expected to return with a revised offer once Gerresheimer's accounting clean-up is complete.",
    source: "Reuters / Yahoo Finance",
    dateRumoured: "2026-04",
    status: "Under Review",
    sector: "Industrials / Pharmaceutical Packaging",
    dealProbability: 42,
    probabilityRationale: "Board rejected April 17 bid — but analysts expect a revised Silgan approach once Gerresheimer resolves its accounting issues by September 2026.",
    keyStats: {
      acquirerMarketCap: "$5.8B",
      targetMarketCap: "$2.8B",
      estimatedPremium: "110%",
      sectorAvgMultiple: "10.5x EV/EBITDA",
    },
  },
  {
    id: "denso-rohm",
    acquirerTicker: "DNZOY",
    acquirerName: "Denso",
    acquirerLogo: "https://logo.clearbit.com/denso.com",
    targetTicker: "ROHCY",
    targetName: "Rohm",
    targetLogo: "https://logo.clearbit.com/rohm.com",
    dealType: "Acquisition",
    estimatedValue: "$8.3B",
    estimatedValueNum: 8.3,
    summary: "Toyota-group automotive components giant Denso made a formal acquisition proposal for Kyoto-based power semiconductor manufacturer Rohm on March 6, 2026, in a deal valued at up to $8.3 billion via a full tender offer. Denso already holds approximately 5% of Rohm, a stake it acquired in September 2025 as a precursor to this approach. Both companies confirmed that discussions are underway, though 'no final decision has been made.' Rohm shares surged 18% on news of the proposal. The strategic rationale is the automotive industry's acute vulnerability to power semiconductor supply constraints exposed during the chip shortages of 2021-2023. Rohm is a Tier 1 global manufacturer of silicon carbide (SiC) power devices — the critical semiconductors governing battery charging and motor drive systems in electric vehicles. For Denso, vertical integration into SiC production would secure supply for Toyota Group's expanding EV lineup. METI (Japan's Ministry of Economy, Trade and Industry) has informally supported the combination.",
    source: "Bloomberg / Nikkei Asia",
    dateRumoured: "2026-03",
    status: "Talks Confirmed",
    sector: "Semiconductors / Automotive",
    dealProbability: 68,
    probabilityRationale: "Formal proposal made March 2026; both companies confirmed discussions — METI support adds political tailwind.",
    keyStats: {
      acquirerMarketCap: "$44B",
      targetMarketCap: "$6.1B",
      estimatedPremium: "38%",
      sectorAvgMultiple: "12.1x EV/EBITDA",
    },
  },
];
