export interface RumouredDeal {
  id: string;
  acquirerTicker: string;
  acquirerName: string;
  acquirerLogo: string;
  targetTicker: string;
  targetName: string;
  targetLogo: string;
  dealType: "Merger" | "Acquisition" | "Buyout" | "PE Deal" | "Strategic Review";
  estimatedValue: string;
  estimatedValueNum: number; // in billions, for sorting
  summary: string;
  source: string;
  dateRumoured: string;
  status: "Rumour" | "Talks Confirmed" | "Under Review";
  sector: string;
}

// Sorted by estimatedValueNum descending (largest deal first)
export const rumouredDeals: RumouredDeal[] = [
  {
    id: "paramount-wbd",
    acquirerTicker: "PARA",
    acquirerName: "Paramount",
    acquirerLogo: "https://logo.clearbit.com/paramount.com",
    targetTicker: "WBD",
    targetName: "Warner Bros. Discovery",
    targetLogo: "https://logo.clearbit.com/wbd.com",
    dealType: "Acquisition",
    estimatedValue: "$110.9B",
    estimatedValueNum: 110.9,
    summary: "In December 2025, Paramount Group — the David Ellison-led entity following Skydance's takeover of the legacy Viacom/CBS business — launched an unsolicited tender offer for Warner Bros. Discovery at $31 per share, valuing WBD at approximately $110.9 billion including debt. The move upended a previously announced $82.7 billion Netflix acquisition of WBD; on February 26, 2026, WBD's board declared Paramount's offer superior and Netflix walked away collecting a $2.8 billion break-up fee. A definitive merger agreement has since been signed.\n\nThe proposed combination would create the world's largest entertainment conglomerate, uniting Paramount Pictures, CBS, MTV, Nickelodeon, Paramount+, and BET with Warner Bros. Pictures, HBO, CNN, DC Studios, Max, and TNT/TBS. The combined company — to be branded Paramount-Warner Bros. — will release more than 30 theatrical films per year across two iconic studios. David Ellison will serve as Chairman and CEO; RedBird Capital's Gerry Cardinale and the Ellison family control the majority voting interest, backed by $47 billion in equity and $54 billion in acquisition debt arranged by Bank of America and Citigroup.\n\nThe deal carries a $7 billion regulatory termination fee — one of the largest in corporate history — reflecting genuine antitrust exposure. The DOJ had already scrutinised the earlier Netflix-WBD deal for potential streaming monopoly concerns; the Paramount-WBD combination faces equivalent review given their combined share of premium scripted content, theatrical distribution, and free-to-air broadcasting. A WBD shareholder vote is scheduled for March 20, 2026, with full close targeted for Q3 2026 subject to DOJ and FCC clearances.",
    source: "Variety / Paramount IR",
    dateRumoured: "2025-12",
    status: "Talks Confirmed",
    sector: "Media / Entertainment",
  },
  {
    id: "musk-openai",
    acquirerTicker: "PRIVATE",
    acquirerName: "Elon Musk Consortium",
    acquirerLogo: "https://logo.clearbit.com/x.com",
    targetTicker: "PRIVATE",
    targetName: "OpenAI",
    targetLogo: "https://logo.clearbit.com/openai.com",
    dealType: "Acquisition",
    estimatedValue: "$97.4B",
    estimatedValueNum: 97.4,
    summary: "In February 2025, Elon Musk — alongside a16z and other venture backers — submitted an unsolicited $97.4 billion all-cash bid for OpenAI, targeting the company during its contentious restructuring from a nonprofit to a Public Benefit Corporation. OpenAI's board unanimously rejected the offer within days, with CEO Sam Altman calling it a strategic distraction rather than a genuine acquisition attempt. The bid was widely seen as set below fair value: OpenAI had recently closed funding at a $157 billion valuation and completed its for-profit restructuring with SoftBank's $40 billion investment at a $260 billion valuation in late 2025.\n\nThe failed takeover has escalated into one of the most consequential legal battles in Silicon Valley history. Musk's lawsuit alleging that Sam Altman and Microsoft deviated from OpenAI's founding nonprofit mission was cleared for a jury trial by a US federal judge who noted there is 'plenty of evidence' that Musk was misled about the organisation's original purpose. The trial is scheduled to begin March 30, 2026. A ruling against OpenAI could force structural changes to its for-profit conversion — potentially reopening acquisition or restructuring scenarios that Musk's camp has sought from the outset.\n\nMeanwhile, OpenAI faces approximately $14 billion in projected operating losses in 2026, renewing analyst debate about whether its current capital-consumption model is sustainable long-term and whether a future strategic transaction — involving xAI, Microsoft, or sovereign capital — remains plausible despite the rejection of Musk's specific bid.",
    source: "Wall Street Journal / Bloomberg",
    dateRumoured: "2025-02",
    status: "Under Review",
    sector: "Artificial Intelligence / Technology",
  },
  {
    id: "up-nsc",
    acquirerTicker: "UNP",
    acquirerName: "Union Pacific",
    acquirerLogo: "https://logo.clearbit.com/up.com",
    targetTicker: "NSC",
    targetName: "Norfolk Southern",
    targetLogo: "https://logo.clearbit.com/nscorp.com",
    dealType: "Merger",
    estimatedValue: "$85B",
    estimatedValueNum: 85,
    summary: "Union Pacific's proposed acquisition of Norfolk Southern, announced in mid-2025, would create the first transcontinental freight railroad in US history — a coast-to-coast network combining Union Pacific's 32,000-route-mile western system with Norfolk Southern's 19,500-route-mile eastern network. The combined enterprise value exceeds $85 billion, making this the largest proposed railroad merger since the Burlington Northern Santa Fe combination in 1995. Management projects $1 billion per year in cost synergies and a 10% improvement in freight car velocity by eliminating interchange bottlenecks at St. Louis, Memphis, and Chicago that currently force cargo transfers between competing railroads.\n\nThe deal has attracted unusual political support: SMART-TD, the largest railroad union, formally backed the combination in a letter to Congress, and President Trump publicly endorsed the merger as consistent with his infrastructure and domestic manufacturing agenda. Single-line transcontinental service would meaningfully reduce trucking volumes on congested interstate corridors — a key argument the companies are advancing with regulators.\n\nThe Surface Transportation Board (STB) — which applies a broad 'public interest' standard that can block deals regardless of antitrust compliance — rejected the initial merger application as procedurally incomplete. Union Pacific submitted notice of intent to refile by end of April 2026. Key opposition includes the Teamsters union and passenger rail advocates concerned about freight traffic crowding Amtrak-shared corridors in the Northeast and Midwest. The STB's multi-year review process means final regulatory resolution is unlikely before 2027-2028.",
    source: "Reuters / Axios",
    dateRumoured: "2025-06",
    status: "Under Review",
    sector: "Transportation / Infrastructure",
  },
  {
    id: "devon-coterra",
    acquirerTicker: "DVN",
    acquirerName: "Devon Energy",
    acquirerLogo: "https://logo.clearbit.com/devonenergy.com",
    targetTicker: "CTRA",
    targetName: "Coterra Energy",
    targetLogo: "https://logo.clearbit.com/coterra.com",
    dealType: "Merger",
    estimatedValue: "$58B",
    estimatedValueNum: 58,
    summary: "Devon Energy and Coterra Energy announced a definitive all-stock merger agreement on February 2, 2026, creating one of the world's largest independent shale operators with pro-forma production exceeding 1.6 million barrels of oil equivalent per day. Devon shareholders will own approximately 54% of the combined company; Coterra shareholders 46%. Devon CEO Clay Gaspar will lead the combined entity; Coterra CEO Tom Jorden becomes non-executive chairman. The combined company retains the Devon Energy name and will be headquartered in Houston.\n\nThe strategic logic centres on multi-basin scale advantages. Devon contributes dominant positions in the Delaware Basin (Permian) and Anadarko Basin; Coterra brings top-tier Permian acreage and the largest single-operator position in the Marcellus Shale. Together, the companies hold approximately 6 million gross acres across five of the top-six US unconventional plays. Management targets $1 billion per year in pre-tax synergies by end of 2027, primarily through supply chain consolidation, lease operating cost reductions, and elimination of redundant corporate infrastructure.\n\nThe combination reflects the broader wave of US energy consolidation driven by institutional investor demands for capital discipline and the competitive pressure created by ExxonMobil's $60 billion Pioneer acquisition and Chevron's $53 billion Hess deal. Devon/Coterra represents the logical next step in mid-major shale consolidation. The deal faces no significant antitrust barriers given the fragmented nature of US unconventional production and is expected to close Q2 2026.",
    source: "Devon Energy IR / Axios",
    dateRumoured: "2026-02",
    status: "Talks Confirmed",
    sector: "Energy / Oil & Gas",
  },
  {
    id: "charter-cox",
    acquirerTicker: "CHTR",
    acquirerName: "Charter Communications",
    acquirerLogo: "https://logo.clearbit.com/charter.com",
    targetTicker: "PRIVATE",
    targetName: "Cox Communications",
    targetLogo: "https://logo.clearbit.com/cox.com",
    dealType: "Acquisition",
    estimatedValue: "$34.5B",
    estimatedValueNum: 34.5,
    summary: "Charter Communications announced the acquisition of Cox Enterprises' cable, commercial fiber, and cloud communications businesses in May 2025 for $34.5 billion — the largest US cable consolidation since Charter's own acquisition of Time Warner Cable in 2016. Cox Communications, the third-largest US cable operator with approximately 7 million residential and business subscribers primarily across the South and Southwest, has been a privately held subsidiary of Cox Enterprises since its founding. The combined company will have 38 million subscribers and be positioned as the definitive cable alternative to the Comcast-NBCUniversal platform.\n\nThe FCC approved the deal in February 2026 with conditions including US job preservation requirements, rural broadband infrastructure investment commitments, and anti-discrimination protections for internet service pricing. The combined company will adopt the Cox Communications brand in markets where Cox currently operates while maintaining the Spectrum brand in legacy Charter territories — a strategy designed to preserve Cox's strong regional brand equity in major metros including Phoenix, Atlanta, Las Vegas, and San Diego.\n\nCalifornia remains the outstanding regulatory hurdle. Charter has formally requested the California Public Utilities Commission to accelerate its review ahead of a September 15, 2026 federal merger condition deadline. FCC Commissioner Brendan Carr backed the deal as consistent with current deregulatory priorities. Full close is expected before September 2026, subject to California approval.",
    source: "Deadline / FCC",
    dateRumoured: "2025-05",
    status: "Talks Confirmed",
    sector: "Telecommunications / Cable",
  },
  {
    id: "merck-rvmd",
    acquirerTicker: "MRK",
    acquirerName: "Merck",
    acquirerLogo: "https://logo.clearbit.com/merck.com",
    targetTicker: "RVMD",
    targetName: "Revolution Medicines",
    targetLogo: "https://logo.clearbit.com/revmed.com",
    dealType: "Acquisition",
    estimatedValue: "$30B",
    estimatedValueNum: 30,
    summary: "The Financial Times reported in January 2026 that Merck is in advanced acquisition talks with Revolution Medicines, the South San Francisco-based oncology biotech, in a deal that could value RVMD at between $28 billion and $32 billion — potentially the largest biotech acquisition since Pfizer's $43 billion purchase of Seagen in 2023. Bloomberg subsequently confirmed the discussions. AbbVie was also reported by the Wall Street Journal to have evaluated Revolution Medicines, though AbbVie publicly denied active negotiations. No formal agreement has been announced as of mid-March 2026.\n\nThe strategic rationale for Merck is as much existential as opportunistic. Keytruda — Merck's flagship PD-1 cancer immunotherapy and the world's best-selling oncology drug at over $25 billion in annual revenue — begins facing biosimilar competition following US patent expiry in 2028. Merck needs a pipeline anchor to sustain its oncology franchise through the 2030s, and Revolution Medicines' RAS(ON) inhibitor platform represents one of the most scientifically validated and commercially significant approaches in the field. KRAS-mutant cancers account for approximately 25% of all human cancers and have historically been considered 'undruggable.' Revolution's lead assets RMC-6236 (pan-RAS inhibitor) and RMC-6291 (KRAS G12C-selective) are in Phase 2/3 trials showing compelling early efficacy and tolerability signals.\n\nRevolution Medicines shares rose approximately 40% on the initial FT report. The company's board retained Morgan Stanley as financial advisor. A formal announcement would likely be framed as Merck's primary pipeline replenishment vehicle for the critical 2028-2032 Keytruda cliff period, following the company's previous unsuccessful attempt to acquire Seagen.",
    source: "Financial Times / Bloomberg",
    dateRumoured: "2026-01",
    status: "Rumour",
    sector: "Pharmaceuticals / Oncology",
  },
  {
    id: "denso-rohm",
    acquirerTicker: "DNZOY",
    acquirerName: "Denso",
    acquirerLogo: "https://logo.clearbit.com/denso.com",
    targetTicker: "PRIVATE",
    targetName: "Rohm",
    targetLogo: "https://logo.clearbit.com/rohm.com",
    dealType: "Acquisition",
    estimatedValue: "$8.3B",
    estimatedValueNum: 8.3,
    summary: "Toyota-group automotive components giant Denso made a formal acquisition proposal for Kyoto-based power semiconductor manufacturer Rohm on March 6, 2026, in a deal valued at up to $8.3 billion via a full tender offer. Denso already holds approximately 5% of Rohm, a stake it acquired in September 2025 as a precursor to this approach. Both companies confirmed that discussions are underway, though 'no final decision has been made.' Rohm shares surged 18% on news of the proposal — their largest single-day gain since 2000.\n\nThe strategic rationale reflects the automotive industry's acute vulnerability to power semiconductor supply constraints, a weakness exposed during the chip shortages of 2021-2023. Rohm is a Tier 1 global manufacturer of silicon carbide (SiC) power devices — the critical semiconductors that govern battery charging, motor drive systems, and DC-DC converters in electric vehicles. SiC adoption is accelerating as automakers design next-generation EV platforms targeting 800-volt architectures that dramatically reduce charging times and extend range. For Denso — Toyota's largest parts supplier and a top-five global auto components company by revenue — vertical integration into SiC semiconductor production would secure supply for Toyota Group's expanding EV lineup and reduce dependence on outside suppliers including ON Semiconductor, STMicroelectronics, and Wolfspeed.\n\nA successful acquisition would represent a significant escalation of Japanese industrial semiconductor consolidation, following the government-backed formation of Rapidus and Renesas's series of bolt-on acquisitions to build domestic advanced chip capability. METI (Japan's Ministry of Economy, Trade and Industry) has informally supported Japanese automotive groups securing domestic semiconductor supply chains.",
    source: "Bloomberg / Nikkei Asia",
    dateRumoured: "2026-03",
    status: "Talks Confirmed",
    sector: "Semiconductors / Automotive",
  },
  {
    id: "apple-peloton",
    acquirerTicker: "AAPL",
    acquirerName: "Apple",
    acquirerLogo: "https://logo.clearbit.com/apple.com",
    targetTicker: "PTON",
    targetName: "Peloton",
    targetLogo: "https://logo.clearbit.com/onepeloton.com",
    dealType: "Acquisition",
    estimatedValue: "$1.8B",
    estimatedValueNum: 1.8,
    summary: "Peloton's Q2 FY2026 earnings report in February 2026 triggered a 23% single-day share price collapse after the company missed consensus estimates on both revenue and subscriber retention, revealing that paid subscription membership had declined over 6% year-over-year to 5.8 million — its lowest level since 2020. The results renewed analyst speculation about Apple making an opportunistic acquisition of the connected fitness platform, now valued at under $2 billion compared to its $50 billion pandemic-era peak. Bloomberg and CNBC have cited sources familiar with Apple's corporate strategy at various points suggesting the company has internally evaluated Peloton on multiple occasions.\n\nThe investment thesis centres on accelerating Apple Fitness+, its subscription workout content service, by acquiring Peloton's 3 million active paid subscribers, proprietary class content library, and hardware design and manufacturing expertise in connected cardio equipment. Integration with Apple Watch, Apple Health, and the broader Apple ecosystem would position Apple as the dominant platform for personal health and fitness — a long-term strategic priority Tim Cook has publicly endorsed as Apple's potential 'greatest contribution to mankind.' The structural synergies are considerable: Peloton's instructor talent and live class infrastructure would immediately elevate Fitness+ beyond its current perceived inferiority relative to Peloton's content library.\n\nHowever, Apple has historically avoided acquiring companies with complex hardware manufacturing operations and significant debt. Peloton carries approximately $700 million in long-term debt and continues to burn cash. Multiple analysts argue that Apple would prefer to license Peloton content or build organically rather than inherit manufacturing complexity. No formal negotiations have been confirmed by either party as of March 2026.",
    source: "Bloomberg / CNBC",
    dateRumoured: "2026-02",
    status: "Rumour",
    sector: "Consumer Technology / Health & Fitness",
  },
];
